# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: git-tui 0.0.3 ruby lib

Gem::Specification.new do |s|
  s.name = "git-tui".freeze
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["andy_maleh".freeze]
  s.date = "2022-02-04"
  s.description = "Git-TUI (Git Text-based User Interface)".freeze
  s.email = "andy.am@gmail.com".freeze
  s.executables = ["git-tui-setup".freeze]
  s.extra_rdoc_files = [
    "CHANGELOG.md",
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "LICENSE.txt",
    "README.md",
    "VERSION",
    "bin/git-tui-setup",
    "lib/git-tui.rb"
  ]
  s.homepage = "http://github.com/AndyObtiva/git-tui".freeze
  s.licenses = ["Apache-2.0".freeze]
  s.post_install_message = "\nTo finish setting up the git-tui Ruby gem in your shell environment, run `git-tui-setup` in order to setup git-tui command and global git aliases/configuration.\n\n".freeze
  s.rubygems_version = "3.3.3".freeze
  s.summary = "Git-TUI (Git Text-based User Interface)".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4
  end

  if s.respond_to? :add_runtime_dependency then
    s.add_runtime_dependency(%q<tty-prompt>.freeze, [">= 0.23.0", "< 2.0.0"])
    s.add_development_dependency(%q<rspec>.freeze, ["~> 3.5"])
    s.add_development_dependency(%q<rdoc>.freeze, ["~> 3.12"])
    s.add_development_dependency(%q<bundler>.freeze, [">= 1.0"])
    s.add_development_dependency(%q<juwelier>.freeze, ["~> 2.1.0"])
    s.add_development_dependency(%q<simplecov>.freeze, [">= 0"])
    s.add_development_dependency(%q<puts_debuggerer>.freeze, [">= 0"])
    s.add_development_dependency(%q<rake-tui>.freeze, [">= 0"])
  else
    s.add_dependency(%q<tty-prompt>.freeze, [">= 0.23.0", "< 2.0.0"])
    s.add_dependency(%q<rspec>.freeze, ["~> 3.5"])
    s.add_dependency(%q<rdoc>.freeze, ["~> 3.12"])
    s.add_dependency(%q<bundler>.freeze, [">= 1.0"])
    s.add_dependency(%q<juwelier>.freeze, ["~> 2.1.0"])
    s.add_dependency(%q<simplecov>.freeze, [">= 0"])
    s.add_dependency(%q<puts_debuggerer>.freeze, [">= 0"])
    s.add_dependency(%q<rake-tui>.freeze, [">= 0"])
  end
end

